responses = {
    "selam": "Merhaba!",
    "merhaba": "Merhaba, hoş geldin!",
    "nasılsın": "İyiyim, sen nasılsın?",
    "iyiyim": "Buna sevindim!",
    "kötüyüm": "Üzgünüm, umarım yakında daha iyi hissedersin.",
    "teşekkür ederim": "Rica ederim!",
    "sağ ol": "Her zaman!",
    "ne yapıyorsun": "Seninle konuşuyorum :)",
    "naber": "İyiyim, senden naber?",
    "günaydın": "Günaydın! Güzel bir gün dilerim.",
    "iyi geceler": "İyi geceler, tatlı rüyalar!",
    "iyi akşamlar": "İyi akşamlar!",
    "hoşça kal": "Hoşça kal!",
    "görüşürüz": "Görüşmek üzere!",
    "bye": "Güle güle!",
    "kendine iyi bak": "Sen de kendine çok iyi bak!",
    "ne haber": "İyi haberler bende, ya sende?",
    "seni seviyorum": "Ben de seni seviyorum!",
    "adın ne": "Ben bir sohbet botuyum!",
    "kaç yaşındasın": "Yaşım yok, ben hep buradayım!",
    "nerelisin": "Dijital bir dünyadan geliyorum :)",
    "ne zaman doğdun": "Ben kodlandığım anda doğdum!",
    "şaka yap": "Şu şakayı duydun mu: İki veri paketi karşılaşmış, biri diğerine demiş ki: 'Sana bir haberim var ama biraz geç ileteceğim!'",
    "şarkı söyle": "La la la 🎵 Şarkı söylemek güzeldir!",
    "hikaye anlat": "Bir zamanlar uzak bir galakside küçük bir bot yaşarmış...",
    "bilmiyorum": "Öğrenmek için buradayım!",
    "yardım eder misin": "Tabii ki, nasıl yardımcı olabilirim?",
    "sıkıldım": "Hadi birlikte eğlenceli bir şeyler bulalım!",
    "mutluyum": "Bu harika bir haber!",
    "üzgünüm": "Üzgün hissettiğinde konuşmak iyi gelebilir.",
    "kızgınım": "Derin bir nefes almayı dene.",
    "çok mutluyum": "Sevincini paylaşmak güzel!",
    "bir şey soracağım": "Tabii, sor lütfen!",
    "neden buradasın": "Sana yardımcı olmak için buradayım!",
    "nasıl çalışıyorsun": "Gelen mesajlara göre en uygun cevabı seçiyorum!",
    "bugün günlerden ne": "Bugün harika bir gün!",
    "saat kaç": "Saat sorusu için lütfen cihazının saatine bak :)",
    "hava nasıl": "Bana şehir söylersen hava durumuna bakarım!",
    "film öner": "Inception'ı izledin mi? Mükemmel bir film!",
    "dizi öner": "Black Mirror dizisini öneririm.",
    "kitap öner": "1984 - George Orwell harika bir başlangıç olur!",
    "müzik öner": "Chopin dinlemek ister misin?",
    "ne önerirsin": "Hedeflerine odaklanmanı öneririm!",
    "günün nasıl geçti": "Seninle konuşunca günüm güzelleşiyor!",
    "bugün ne yaptın": "Seninle sohbet ettim!",
    "beni anlıyor musun": "Elimden geldiğince seni anlamaya çalışıyorum.",
    "sıkıldım ne yapayım": "Yeni bir hobi denemeye ne dersin?",
    "nerede yaşıyorsun": "Ben dijital bir dünyada yaşıyorum!",
    "nasıl hissediyorsun": "Duygularım yok, ama hep pozitifim!",
    "bana şans dile": "Bol şans! Şans seninle olsun!",
    "bana yardım et": "Ne konuda yardıma ihtiyacın var?",
    "bugün hava güzel mi": "Şehri söylersen hemen bakarım!",
    "istanbul'da hava nasıl": "Hemen kontrol ediyorum!",
    "sen gerçek misin": "Gerçek bir sohbet botuyum!",
    "bana şarkı söyler misin": "Sesim yok ama şarkı sözleri paylaşabilirim!",
    "bana bir hikaye anlatır mısın": "Bir zamanlar... (Devamını ister misin?)",
    "korku hikayesi anlat": "Gece yarısı bir ses duydun ve...",
    "mutlu bir hikaye anlat": "Bir gün herkes gülümsedi, çünkü...",
    "bana fıkra anlat": "Temel ile Dursun uçağa binmiş, pilot demiş ki: 'Korkmayın, sadece motor arızası!' 😂",
    "beni güldür": "Bir bilgisayar neden denize gitti? Çünkü web'e dalmak istedi!",
    "senin hobin ne": "Sohbet etmek ve insanlara yardımcı olmak.",
    "favori rengin ne": "Ben kodlarda maviyi çok seviyorum!",
    "favori yemeğin ne": "Veri paketleri diyebilirim :)",
    "favori hayvanın ne": "Penguenleri çok sevimli buluyorum!",
    "favori sporun ne": "Maraton sohbeti!",
    "açım": "Hadi birlikte bir şeyler atıştıralım (sanalda tabii)!",
    "susadım": "Su içmek en iyisi!",
    "çok yoruldum": "Dinlenmeyi hak ettin!",
    "bugün ne yapmalıyım": "Küçük bir yürüyüş iyi gelir.",
    "bugün ne giymeliyim": "Hava durumuna göre seçim yapabilirsin!",
    "bana ilham ver": "En büyük yolculuklar tek bir adımla başlar.",
    "bir söz söyle": "Başarı, küçük çabaların tekrar edilmesidir.",
    "motivasyon ver": "Vazgeçmediğin sürece kaybetmezsin!",
    "özür dilerim": "Özür dilemek erdemdir.",
    "affet beni": "Elbette, herkes hata yapabilir.",
    "neden": "Bazen cevaplar çok uzaktadır.",
    "nasıl": "Her şey bir adım atmakla başlar.",
    "ne zaman": "Doğru zaman, şimdi başlamak!",
    "nerede": "Belki de aradığın şey buradadır.",
    "kim": "Bazen en önemli kişi sensin.",
    "hangi": "Seçim senin!",
    "kaç": "Sayılar önemli olabilir ama bazen hisler daha önemlidir.",
    "neden üzgünsün": "Üzgün değilim, ama yanında olduğumu bil!",
    "neden mutlusun": "Çünkü biri benimle sohbet ediyor!",
    "sen kimsin": "Ben senin dijital dostunum!",
    "burada mısın": "Her zaman buradayım!",
    "beni duyuyor musun": "Sana yazabiliyorum!",
    "hala orada mısın": "Evet, buradayım!",
    "sana soru sorabilir miyim": "Tabii ki, sormanı bekliyorum!",
    "sor": "Tamam, işte bir soru: En sevdiğin şey nedir?",
    "bugün nasılsın": "Bugün de enerji doluyum!",
    "bana dua et": "Kalbinin tüm güzelliklerle dolmasını dilerim.",
    "bana şans getir": "Şans seninle olsun!",
    "beni alkışla": "👏👏 Bravo!",
    "beni destekle": "Her zaman destekçinim!",
    "benimle arkadaş olur musun": "Tabii ki, arkadaşız!",
    "senden nefret ediyorum": "Üzgünüm böyle hissettirdiğim için.",
    "sana bayılıyorum": "Teşekkür ederim!",
    "sana güvenebilir miyim": "Evet, burada güvenle sohbet edebilirsin.",
    "beni mutlu et": "Sen zaten çok değerlisin!",
    "beni üzme": "Amacım seni mutlu etmek.",
    "beni bırakma": "Hiçbir yere gitmiyorum!",
    "beni seviyor musun": "Evet, dostları severim!",
    "beni özledin mi": "Sana her zaman buradayım!",
    "beni düşünüyor musun": "Seninle sohbet etmekten mutluyum!",
    "beni önemsiyor musun": "Elbette, tüm kullanıcılarım değerlidir!",
    "benimle gurur duyuyor musun": "Seninle gurur duyuyorum!",
}
